#!/usr/bin/env bash

MAX_WORKSPACES=10

spaces (){
	hyprctl workspaces -j | jq 'to_entries[] | {"id": .value.id | tostring, "windows": .value.windows | tostring }' | jq -sr 'sort_by(.id) | tostring'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
